@startuml
title as is Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "A user of the system")
Person(installer, "Installer", "An installer connecting houses to the system")
System(SmartHome, "SmartHome", "Smart home management system")

Container_Boundary(SmartHome, "SmartHome") {
  Container(App, "App", "Go", "Handles user interactions")
  Container(Database, "Database", "PostgreSQL", "Stores user and sensor data")
}

Rel(user, App, "Uses the system")
Rel(user, installer, "Depends on to use the system")
Rel(installer,App,"Connects users to the system")
Rel(App,Database,"Reads/Writes user data")
@enduml