@startuml
title As-Is Context Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "House owner")
Person(installer, "Installer", "Specialist who installs devices")
System(SmartHome, "SmartHome", "Heating control system")
System_Ext(devices, "Heating Devices", "Sensors and relays installed in the house")

Rel(user, SmartHome, "Uses")
Rel(installer, devices, "Installs")
Rel(installer, SmartHome, "Connects devices")
Rel(SmartHome, devices, "Polls temperature and sends commands")

@enduml