@startuml
title To-Be Telemetry Component Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Container_Boundary(telemetry, "Telemetry Service") {
  Component(api, "API", "HTTP Controller", "Accepts telemetry requests")
  Component(app, "Application Service", "Application Service", "Coordinates telemetry operations")
  Component(repo, "Repository", "Repository", "Reads and writes telemetry")
  Component(subscriber, "Event Subscriber", "Adapter", "Reads telemetry events")
}

Rel(api, app, "Uses")
Rel(app, repo, "Uses")
Rel(app, subscriber, "Uses")
@enduml